allowed_external_types = [
    "aws_smithy_types::body::SdkBody",
    "aws_smithy_types::config_bag::storable::StoreReplace",
    "aws_smithy_types::config_bag::storable::Storable",
    "bytes::bytes::Bytes",
    "http::header::map::HeaderMap",
    "http::header::name::HeaderName",
    "http::header::value::HeaderValue",
    "http_body::Body",
]
