on:
  workflow_dispatch:

name: Update GitHub Pages

env:
  rust_version: 1.78.0

# Allow only one doc pages build to run at a time for the entire smithy-rs repo
concurrency:
  group: github-pages-yml
  cancel-in-progress: true

jobs:
  update-lockfiles-branch-name:
    name: Generate release branch name
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.branch-name-generation.outputs.branch_name }}
    steps:
    - name: Get or create release branch
      id: branch-name-generation
      shell: bash
      run: |
        update_lockfiles_branch="update-all-lockfiles-$(date +%s)"
        echo "branch_name=${update_lockfiles_branch}" > $GITHUB_OUTPUT

  push-updated-lockfiles-to-branch:
    name: push-to-branch
    needs:
    - update-lockfiles-branch-name
    runs-on: ubuntu-latest
    steps:
    - name: Checkout smithy-rs
      uses: actions/checkout@v4
      with:
        ref: main
        path: smithy-rs
        token: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
    - name: Cargo update all lockfiles
      uses: ./smithy-rs/.github/actions/docker-build
      with:
        action: cargo-update-lockfiles
        action-arguments: ${{ needs.update-lockfiles-branch-name.outputs.branch_name }}

  create-pull-request:
    name: Create pull request
    needs:
    - update-lockfiles-branch-name
    - push-updated-lockfiles-to-branch
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_AUTOMATION_BOT_PAT }}
        BRANCH_NAME: ${{ needs.update-lockfiles-branch-name.outputs.branch_name }}
      run: |
        echo ${BRANCH_NAME}
        echo ${{ needs.update-lockfiles-branch-name.outputs.branch_name }}
